python train_iu.py \
  --exp_name "resnet-diff-iu-0" \
  --epochs 50 \
  --dataset "iu_xray" \
  --ve_name "resnet" \
  --use_diff \
  --use_gca \
  --lr_ed 5e-4 \
  --lr_ve 2e-4 \
  --warmup_epochs 10 \
  --weight_decay 1e-5 \
  --channel_reduction 4 \
  --num_layers 2 \
  --save_path "results" \
  --batch_size 64 \
  --accum_steps 1 \
  --early_stopping 10 \
  --max_length 50 \
  --step_size 10 \
  --max_gen 100 \
  --hidden_size 512 \
  --fc_size 512 \
  --contrastive_proj_dim 256 \
  --vocab_size 1642 \
  --delta1 1 \
  --delta2 0.3 \
  --topk 3 \
  --temperature 1 \
  --lambda_init 0.8 \
  --dropout 0.0 \
  --beam_width 3 \
  --encoder_size 2048 \
  --num_heads 8 \
  --diff_num_heads 4 \
  --num_workers 16 \
  --image_path "/data" \
  --ann_path "iu_xray" \
  --project_root "/workspace/D-ExpertTransformer" \


